# Generated by Django 5.2.7 on 2026-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0006_documentchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='rfp_team_size_required',
        ),
        migrations.AlterField(
            model_name='companycapability',
            name='expected_emd_in_inr',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companycapability',
            name='expected_timeline_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companycapability',
            name='max_budget',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='companycapability',
            name='min_budget',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='extraction_confidence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='extraction_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='no_of_days_for_analysis',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='no_of_days_for_submission',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='rfp_budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='rfp_emd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='rfp_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='rfp_timeline_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfpevaluation',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
    ]
