# Generated by Django 5.2.7 on 2026-02-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0007_remove_document_rfp_team_size_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True)),
                ('technical_approach', models.TextField(blank=True)),
                ('timeline', models.TextField(blank=True)),
                ('compliance_checklist', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='generation.document')),
            ],
        ),
    ]
